name: rzv-ai-sdk-collection
base: core24
version: '1.0'
summary: Renesas RZ/V AI SDK Examples (V2H, cross-compiled)
description: |
  Selected AI examples from renesas-rz/rzv_ai_sdk, built for PRODUCT=V2H.
  TVM runtime is staged from renesas-rz/rzv_drp-ai_tvm.

grade: devel
confinement: devmode

platforms:
  arm64:
    build-on: [amd64,arm64]
    build-for: [arm64]

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

package-repositories:
  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    formats: [deb, deb-src]
    components: [main, universe]
    suites: [noble, noble-updates, noble-backports]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    formats: [deb, deb-src]
    components: [main]
    suites: [noble]
    key-id: 1E72A68F43DA1C8E4BB7B59356451E45B00B4CB5
    url: http://ppa.launchpad.net/ubuntu-on-renesas/public-ppa/ubuntu

parts:
  tvm-runtime:
    plugin: nil
    source: https://github.com/renesas-rz/rzv_drp-ai_tvm.git
    source-type: git
    override-build: |
      set -eux
      ls -l $CRAFT_PART_SRC
      mkdir -p "$CRAFT_PART_INSTALL/usr/local/tvm"
      cp -a $CRAFT_PART_SRC/tvm $CRAFT_PART_INSTALL/usr/local/tvm/

      # Follow Renesas Dockerfile setup
      cp -a $CRAFT_PART_SRC/setup/include/*.h $CRAFT_PART_INSTALL/usr/local/tvm/tvm/include/tvm/runtime

      # Copy to TVM folder to match with CMakefiles
      mkdir -p $CRAFT_PART_INSTALL/usr/local/tvm/obj/build_runtime/v2m/lib/
      cp -a $CRAFT_PART_SRC/obj/build_runtime/v2m/lib/* $CRAFT_PART_INSTALL/usr/local/tvm/obj/build_runtime/v2m/lib/

      # Workaround without the libc header from kernel
      mkdir -p $CRAFT_PART_INSTALL/usr/local/tvm/tvm/include/linux
      cp ${CRAFT_PROJECT_DIR}/drpai.h $CRAFT_PART_INSTALL/usr/local/tvm/tvm/include/linux

    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/usr/lib/
      # Install runtime library
      cp -a $CRAFT_PART_SRC/obj/build_runtime/v2m/lib/* $CRAFT_PRIME/usr/lib/

      # Remove TVM
      rm -rf $CRAFT_PRIME/usr/local/tvm/

  rz-ai-sdk-src:
    after: [tvm-runtime]
    plugin: nil
    source: https://github.com/renesas-rz/rzv_ai_sdk.git
    source-type: git
    source-tag: v6.20
    override-build: |
      # Patch CMakefiles for correct TVM run time library and add install support
      git apply -v ${CRAFT_PROJECT_DIR}/cmake.patch
      git apply -v ${CRAFT_PROJECT_DIR}/cam_gst.patch
      craftctl default
    build-packages:
      - cmake
      - ninja-build
      - pkg-config
      - gcc-aarch64-linux-gnu
      - g++-aarch64-linux-gnu
      - libopencv-dev:$CRAFT_ARCH_BUILD_FOR
      - libopencv-video-dev:$CRAFT_ARCH_BUILD_FOR
      - libopencv-highgui-dev:$CRAFT_ARCH_BUILD_FOR
      - libopencv-imgproc-dev:$CRAFT_ARCH_BUILD_FOR
      - libopencv-imgcodecs-dev:$CRAFT_ARCH_BUILD_FOR
      - libopencv-videoio-dev:$CRAFT_ARCH_BUILD_FOR
      - libwayland-dev:$CRAFT_ARCH_BUILD_FOR
      - libgles-dev:$CRAFT_ARCH_BUILD_FOR
      - libtesseract-dev:$CRAFT_ARCH_BUILD_FOR
      - libboost1.83-dev:$CRAFT_ARCH_BUILD_FOR
      - libmmngr-dev:$CRAFT_ARCH_BUILD_FOR
      - libmmngrbuf-dev:$CRAFT_ARCH_BUILD_FOR
      - linux-libc-dev-renesas
    stage-packages:
      - libmmngr1:$CRAFT_ARCH_BUILD_FOR
      - libmmngrbuf1:$CRAFT_ARCH_BUILD_FOR
      - libopencv-video406t64:$CRAFT_ARCH_BUILD_FOR
      - libopencv-highgui406t64:$CRAFT_ARCH_BUILD_FOR
      - libopencv-imgproc406t64:$CRAFT_ARCH_BUILD_FOR
      - libopencv-imgcodecs406t64:$CRAFT_ARCH_BUILD_FOR
      - libopencv-videoio406t64:$CRAFT_ARCH_BUILD_FOR
      - libopencv-contrib406t64:$CRAFT_ARCH_BUILD_FOR
      - libtesseract5:$CRAFT_ARCH_BUILD_FOR
      - v4l-utils:$CRAFT_ARCH_BUILD_FOR
      - gstreamer1.0-plugins-good:$CRAFT_ARCH_BUILD_FOR
      - qtwayland5:$CRAFT_ARCH_BUILD_FOR
      - xkb-data:$CRAFT_ARCH_BUILD_FOR
    prime:
      - -usr/lib/x86_64-linux-gnu

  object-detection-model:
    after: [r01-object-detection]
    source: https://github.com/renesas-rz/rzv_ai_sdk/releases/download/v6.20/R01_object_detection_deploy_tvm_v2h-v251.so
    source-type: file
    plugin: dump
    organize:
      R01_object_detection_deploy_tvm_v2h-v251.so: usr/r01/bin/yolov3_onnx/deploy.so

  q01-footfall-counter:
    after: [rz-ai-sdk-src]
    plugin: cmake
    source: ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/Q01_footfall_counter/src
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/q01
      - -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
      - -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    build-environment:
      - PRODUCT: V2H
      - TVM_HOME: $CRAFT_STAGE/usr/local/tvm/tvm
    build-packages:
      - wayland-protocols
      - libwayland-bin  # provides wayland-scanner
    override-build: |
      # Generate the file where the CMakeLists.txt expects it
      mkdir -p /usr/src/debug/gstreamer1.0-plugins-base/1.22.12/gst-libs/gst/gl/
      wayland-scanner private-code \
        /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
        /usr/src/debug/gstreamer1.0-plugins-base/1.22.12/gst-libs/gst/gl/xdg-shell-client-protocol.c
      # Generate the header
      wayland-scanner client-header \
        /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
        /usr/src/debug/gstreamer1.0-plugins-base/1.22.12/gst-libs/gst/gl/xdg-shell-client-protocol.h
      mkdir -p $CRAFT_PART_INSTALL/usr/q01/bin/
      cp -a ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/Q01_footfall_counter/exe_v2h/* $CRAFT_PART_INSTALL/usr/q01/bin/
      craftctl default
    override-prime: |
      craftctl default
      cp -a ${CRAFT_PROJECT_DIR}/launch-object-tracker.sh $CRAFT_PRIME/usr/q01/bin/

  q08-object-counter:
    after: [rz-ai-sdk-src]
    plugin: cmake
    source: ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/Q08_object_counter/src
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/q08
      - -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
      - -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    build-environment:
      - PRODUCT: V2H
      - TVM_HOME: $CRAFT_STAGE/usr/local/tvm/tvm
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/q08/bin/
      cp -a ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/Q08_object_counter/exe_v2h/* $CRAFT_PART_INSTALL/usr/q08/bin/
      craftctl default
    override-prime: |
      craftctl default
      cp -a ${CRAFT_PROJECT_DIR}/launch-object-counter.sh $CRAFT_PRIME/usr/q08/bin/

  r01-object-detection:
    after: [rz-ai-sdk-src]
    plugin: cmake
    source: ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/R01_object_detection/src
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/r01
      - -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
      - -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    build-environment:
      - PRODUCT: V2H
      - TVM_HOME: $CRAFT_STAGE/usr/local/tvm/tvm
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/r01/bin/
      cp -a ${CRAFT_PROJECT_DIR}/../parts/rz-ai-sdk-src/src/R01_object_detection/exe_v2h/* $CRAFT_PART_INSTALL/usr/r01/bin/
      craftctl default
    override-prime: |
      craftctl default
      cp -a ${CRAFT_PROJECT_DIR}/launch-object-detection.sh $CRAFT_PRIME/usr/r01/bin/

  gpu-2404:
    after: [q01-footfall-counter, q08-object-counter, r01-object-detection]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper

apps:
  object-tracker:
    command-chain:
    - bin/gpu-2404-wrapper
    command: usr/q01/bin/launch-object-tracker.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/aarch64-linux-gnu/pulseaudio
      XDG_RUNTIME_DIR: /run/user/1000
      WAYLAND_DISPLAY: wayland-0
      QT_QPA_PLATFORM: wayland-egl
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/aarch64-linux-gnu/qt5/plugins
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d
    plugs: [camera, opengl, wayland, hardware-observe, gpu-2404]

  object-counter:
    command-chain:
    - bin/gpu-2404-wrapper
    command: usr/q08/bin/launch-object-counter.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/aarch64-linux-gnu/pulseaudio
      XDG_RUNTIME_DIR: /run/user/1000
      WAYLAND_DISPLAY: wayland-0
      QT_QPA_PLATFORM: wayland-egl
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/gpu-2404/lib/qt5/plugins
      XKB_CONFIG_ROOT: $SNAP/gpu-2404-2/share/X11/xkb
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gpu-2404-2/share/glvnd/egl_vendor.d
    plugs: [camera, opengl, wayland, hardware-observe, gpu-2404]

  object-detection:
    command-chain:
    - bin/gpu-2404-wrapper
    command: usr/r01/bin/launch-object-detection.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/aarch64-linux-gnu/pulseaudio
      XDG_RUNTIME_DIR: /run/user/1000
      WAYLAND_DISPLAY: wayland-0
      QT_QPA_PLATFORM: wayland-egl
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/gpu-2404/lib/qt5/plugins
      XKB_CONFIG_ROOT: $SNAP/gpu-2404-2/share/X11/xkb
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gpu-2404-2/share/glvnd/egl_vendor.d
    plugs: [camera, opengl, wayland, hardware-observe, gpu-2404]
